### ISSUE TITLE
Update 3.12.1 Sharing Crystal in chat kills server

### ISSUE THREAD

**Issue by bildwerktv** [BONNePlayground/VaultHuntersDiscordIntegrator#6]
### Expected behavior

Showing the crystal in discord

### Observed/Actual behavior

Server crashes

### Steps/models to reproduce

Start 3.12.1 Server with DiscordIntegration
Share crystal in chat

### VaultHunters version

3.12.1

### Other

`Time: 11/10/23, 2:04 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'iskallia.vault.item.crystal.CrystalModifiers iskallia.vault.item.crystal.CrystalData.getModifiers()'
	at lv.id.bonne.vhdiscord.parser.VaultItemsHandler.handleVaultCrystalTooltip(VaultItemsHandler.java:577) ~[VaultHuntersDiscordIntegration-1.4.1-1.18.2.jar%23195!/:1.4.1] {re:mixin,re:classloading}
	at lv.id.bonne.vhdiscord.parser.VaultItemsHandler.generateVaultHuntersItemTooltips(VaultItemsHandler.java:124) ~[VaultHuntersDiscordIntegration-1.4.1-1.18.2.jar%23195!/:1.4.1] {re:mixin,re:classloading}
	at de.erdbeerbaerlp.dcintegration.forge.util.ForgeMessageUtils.craftVaultHuntersItemMessage(ForgeMessageUtils.java:761) ~[dcintegration-forge-2.5.0-1.18.2.jar%2384!/:2.5.0] {re:mixin,re:classloading,pl:mixin:APP:mixins.vhdiscord.dcintegration.json:MixinForgeMessageUtils,pl:mixin:A}
	at de.erdbeerbaerlp.dcintegration.forge.util.ForgeMessageUtils.parseJsonArgs(ForgeMessageUtils.java:640) ~[dcintegration-forge-2.5.0-1.18.2.jar%2384!/:2.5.0] {re:mixin,re:classloading,pl:mixin:APP:mixins.vhdiscord.dcintegration.json:MixinForgeMessageUtils,pl:mixin:A}
	at de.erdbeerbaerlp.dcintegration.forge.util.ForgeMessageUtils.searchAndParseArray(ForgeMessageUtils.java:604) ~[dcintegration-forge-2.5.0-1.18.2.jar%2384!/:2.5.0] {re:mixin,re:classloading,pl:mixin:APP:mixins.vhdiscord.dcintegration.json:MixinForgeMessageUtils,pl:mixin:A}
	at de.erdbeerbaerlp.dcintegration.forge.util.ForgeMessageUtils.genItemStackEmbedIfAvailable(ForgeMessageUtils.java:568) ~[dcintegration-forge-2.5.0-1.18.2.jar%2384!/:2.5.0] {re:mixin,re:classloading,pl:mixin:APP:mixins.vhdiscord.dcintegration.json:MixinForgeMessageUtils,pl:mixin:A}
	at de.erdbeerbaerlp.dcintegration.forge.DiscordIntegration.chat(DiscordIntegration.java:278) ~[dcintegration-forge-2.5.0-1.18.2.jar%2384!/:2.5.0] {re:classloading,re:mixin}
	at net.minecraftforge.eventbus.ASMEventHandler_142_DiscordIntegration_chat_ServerChatEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at vazkii.quark.content.management.module.ItemSharingModule.linkItem(ItemSharingModule.java:113) ~[Quark-3.2-358.jar%23156!/:3.2-358] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at vazkii.quark.base.network.message.LinkItemMessage.lambda$receive$0(LinkItemMessage.java:31) ~[Quark-3.2-358.jar%23156!/:3.2-358] {re:classloading}
	at net.minecraftforge.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:213) ~[forge-1.18.2-40.2.9-universal.jar%23209!/:?] {re:classloading}
	at vazkii.quark.base.network.message.LinkItemMessage.receive(LinkItemMessage.java:31) ~[Quark-3.2-358.jar%23156!/:3.2-358] {re:classloading}
	at vazkii.arl.network.NetworkHandler.lambda$register$2(NetworkHandler.java:64) ~[AutoRegLib-1.7-53.jar%2348!/:1.7-53] {re:classloading}
	at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:115) ~[forge-1.18.2-40.2.9-universal.jar%23209!/:?] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.minecraftforge.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:115) ~[forge-1.18.2-40.2.9-universal.jar%23209!/:?] {re:classloading}
	at net.minecraftforge.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:153) ~[forge-1.18.2-40.2.9-universal.jar%23209!/:?] {re:classloading}
	at net.minecraftforge.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:72) ~[forge-1.18.2-40.2.9-universal.jar%23209!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:SimpleChannelMixin,pl:mixin:A}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:68) ~[forge-1.18.2-40.2.9-universal.jar%23209!/:?] {re:classloading}
	at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78) ~[forge-1.18.2-40.2.9-universal.jar%23209!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:core.NetworkHooksMixin,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinNetworkHooks,pl:mixin:A}
	at java.util.Optional.map(Optional.java:260) ~[?:?] {re:mixin}
	at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78) ~[forge-1.18.2-40.2.9-universal.jar%23209!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:core.NetworkHooksMixin,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinNetworkHooks,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7423_(ServerGamePacketListenerImpl.java:1440) ~[server-1.18.2-20220404.173914-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:35) ~[server-1.18.2-20220404.173914-srg.jar%23204!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:networkstats.CCustomPayloadPacketNameMixin,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:8) ~[server-1.18.2-20220404.173914-srg.jar%23204!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:networkstats.CCustomPayloadPacketNameMixin,pl:mixin:A}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.18.2-20220404.173914-srg.jar%23204!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23204!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%23204!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[server-1.18.2-20220404.173914-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flan.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:AccessorMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[server-1.18.2-20220404.173914-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flan.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:AccessorMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[server-1.18.2-20220404.173914-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flan.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:AccessorMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[server-1.18.2-20220404.173914-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flan.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:AccessorMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.18.2-20220404.173914-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:761) ~[server-1.18.2-20220404.173914-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flan.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:AccessorMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[server-1.18.2-20220404.173914-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flan.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:AccessorMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flan.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:AccessorMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) [?:?] {re:mixin}
`

**Comment by BONNe** [comment]
Yes, sorry, the 1.4.1 is not compatible with the newest Vault Hunters version.
The update 1.5.0 has been pushed to CurseForge but is currently in a review status.

**Comment by bildwerktv** [comment]
Thanks for your work, the update fixed the issue
